name: Deploy Latest Playground

on:
  push:
    branches:
      - latest-release-website
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'yarn'
    - name: Install Dependencies
      run: yarn

    - name: Install Dependencies
      run: yarn build

    - name: Deploy
      run: ./deploy/deploy_latest.sh