name: Master Playground

on:
  pull_request: #change to push if it works
    branches: [ master ]
jobs:
    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js environment
      uses: actions/setup-node@v3.2.0
      with:
        node-version: 16
        cache: 'yarn'

    - name: Install and Build
      run: |
        yarn install
        yarn build
        yarn build:playground
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4.3.3
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: packages/playground/dist # The folder the action should deploy.
        target-folder: master
        clean: true